dist: focal
sudo: required

services: docker

language: python
python:
  - "3.8"

branches:
  only:
    - master

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.deb
  - sudo dpkg -i hugo_0.76.5_Linux-64bit.deb

script:
  - hugo
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker build -t $DOCKER_USER/tangelov-me:latest .
  - docker push $DOCKER_USER/tangelov-me:latest
