name: Tangelov GH Actions To DockerHub
on: 
  push:
    branches:
      - 'post/github-actions-i-bis'

jobs:
  docker-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Setup Hugo in Github Actions
        uses: peaceiris/actions-hugo@v2

      - name: Build Hugo static content
        run: hugo --minify

      - name: Save output for next steps
        uses: actions/cache@v2
        with:
          path: public
          key: public

      - name: Docker Login using Github Action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push using Github Action
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: | 
            ${{ secrets.DOCKER_USER }}/tangelov-me:latest
            ${{ secrets.DOCKER_USER }}/tangelov-me:${{ env.COMMIT_SHORT_SHA }}
