name: Tangelov GH Actions To DockerHub
on: 
  push:
    branches:
      - 'post/github-actions-i-bis'

jobs:
  Create-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
          submodules: true  # Gathering themes
          fetch-depth: 0

      - name: Setup Hugo in Github Actions
        uses: peaceiris/actions-hugo@v2
        run: hugo --minify

      - name: Save output for next steps
        uses: actions/cache@v2
        with:
          path: public
          key: public

      - name: Docker Login using Github Action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push using Github Action
        uses: docker/build-push-action@v5
        run: ls -lah
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/tangelov-me:latest
